const express = require('express');
const PptxGenJS = require('pptxgenjs');
const fs = require('fs');
const path = require('path');
const axios = require('axios');
const FormData = require('form-data');
const { v4: uuidv4 } = require('uuid');
const MediaGeneration = require('../models/MediaGeneration');
const { authenticateToken } = require('../middleware/auth');

const router = express.Router();

// Text generation (ChatGPT-like)
router.post('/text', authenticateToken, async (req, res) => {
  try {
    const { prompt, context } = req.body;
    
    // Simulate AI text generation (replace with actual AI API)
    const response = await generateTextResponse(prompt, context);
    
    res.json({
      content: response,
      type: 'text'
    });
  } catch (error) {
    res.status(500).json({ message: 'Text generation failed', error: error.message });
  }
});

// Image generation
router.post('/image', authenticateToken, async (req, res) => {
  try {
    const { prompt, style = 'realistic', size = '1024x1024' } = req.body;
    
    // Simulate image generation (replace with actual AI API)
    const imageUrl = await generateImage(prompt, style, size);
    
    // Save to database
    const mediaGen = new MediaGeneration({
      userId: req.userId,
      type: 'image',
      prompt,
      style,
      outputUrl: imageUrl,
      metadata: { size }
    });
    
    await mediaGen.save();
    
    res.json({
      title: `Generated Image: ${prompt.substring(0, 50)}...`,
      style,
      prompt,
      imageUrl,
      type: 'image'
    });
  } catch (error) {
    res.status(500).json({ message: 'Image generation failed', error: error.message });
  }
});

// Video generation
router.post('/video', authenticateToken, async (req, res) => {
  try {
    const { prompt, style = 'cinematic', duration = '5s', aspectRatio = '16:9' } = req.body;
    
    // Simulate video generation (replace with actual AI API)
    const videoUrl = await generateVideo(prompt, style, duration, aspectRatio);
    
    // Save to database
    const mediaGen = new MediaGeneration({
      userId: req.userId,
      type: 'video',
      prompt,
      style,
      outputUrl: videoUrl,
      metadata: { duration, aspectRatio }
    });
    
    await mediaGen.save();
    
    res.json({
      title: `Generated Video: ${prompt.substring(0, 50)}...`,
      duration,
      style,
      prompt,
      videoUrl,
      type: 'video'
    });
  } catch (error) {
    res.status(500).json({ message: 'Video generation failed', error: error.message });
  }
});

// PPT generation
router.post('/ppt', authenticateToken, async (req, res) => {
  try {
    const { content, title = 'Generated Presentation', theme = 'default' } = req.body;
    
    const filename = `${uuidv4()}.pptx`;
    const filepath = path.join(__dirname, '../uploads', filename);
    
    // Ensure uploads directory exists
    const uploadsDir = path.dirname(filepath);
    if (!fs.existsSync(uploadsDir)) {
      fs.mkdirSync(uploadsDir, { recursive: true });
    }
    
    // Create PowerPoint presentation
    const pptx = new PptxGenJS();
    
    // Set presentation properties
    pptx.author = 'Kris Bot';
    pptx.company = 'Kris Bot AI';
    pptx.title = title;
    
    // Title slide
    const titleSlide = pptx.addSlide();
    titleSlide.addText(title, {
      x: 1, y: 2, w: 8, h: 1.5,
      fontSize: 32,
      bold: true,
      align: 'center',
      color: '363636'
    });
    titleSlide.addText('Generated by Kris Bot', {
      x: 1, y: 4, w: 8, h: 0.5,
      fontSize: 16,
      align: 'center',
      color: '666666'
    });
    
    // Content slides - split content into slides
    const contentLines = content.split('\n').filter(line => line.trim());
    const slidesContent = [];
    let currentSlide = [];
    
    contentLines.forEach(line => {
      if (line.startsWith('#') || currentSlide.length >= 5) {
        if (currentSlide.length > 0) {
          slidesContent.push(currentSlide);
          currentSlide = [];
        }
      }
      currentSlide.push(line);
    });
    
    if (currentSlide.length > 0) {
      slidesContent.push(currentSlide);
    }
    
    // Add content slides
    slidesContent.forEach((slideContent, index) => {
      const slide = pptx.addSlide();
      
      // Slide title
      const slideTitle = slideContent[0].replace(/^#+\s*/, '') || `Slide ${index + 1}`;
      slide.addText(slideTitle, {
        x: 0.5, y: 0.5, w: 9, h: 1,
        fontSize: 24,
        bold: true,
        color: '363636'
      });
      
      // Slide content
      const bulletPoints = slideContent.slice(1).map(line => line.replace(/^-\s*/, ''));
      if (bulletPoints.length > 0) {
        slide.addText(bulletPoints, {
          x: 0.5, y: 1.8, w: 9, h: 4,
          fontSize: 16,
          bullet: true,
          color: '444444'
        });
      }
    });
    
    // Save presentation
    await pptx.writeFile({ fileName: filepath });
    
    const pptUrl = `/uploads/${filename}`;
    
    // Save to database
    const mediaGen = new MediaGeneration({
      userId: req.userId,
      type: 'ppt',
      prompt: `PPT: ${title}`,
      outputUrl: pptUrl,
      metadata: { theme, title }
    });
    
    await mediaGen.save();
    
    res.json({
      title: `Generated PPT: ${title}`,
      pptUrl,
      filename,
      type: 'ppt'
    });
  } catch (error) {
    res.status(500).json({ message: 'PPT generation failed', error: error.message });
  }
});

// Resume generation
router.post('/resume', authenticateToken, async (req, res) => {
  try {
    const { personalInfo, experience, education, skills, template = 'modern' } = req.body;
    
    const filename = `${uuidv4()}.pptx`;
    const filepath = path.join(__dirname, '../uploads', filename);
    
    // Ensure uploads directory exists
    const uploadsDir = path.dirname(filepath);
    if (!fs.existsSync(uploadsDir)) {
      fs.mkdirSync(uploadsDir, { recursive: true });
    }
    
    // Create PowerPoint resume
    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_WIDE';
    
    const slide = pptx.addSlide();
    
    // Header with name and contact
    slide.addText(personalInfo.name || 'Your Name', {
      x: 0.5, y: 0.5, w: 9, h: 0.8,
      fontSize: 28,
      bold: true,
      color: '2E4057'
    });
    
    const contactInfo = [
      personalInfo.email || 'email@example.com',
      personalInfo.phone || '+1 (555) 123-4567',
      personalInfo.location || 'City, State'
    ].join(' | ');
    
    slide.addText(contactInfo, {
      x: 0.5, y: 1.2, w: 9, h: 0.4,
      fontSize: 12,
      color: '666666'
    });
    
    // Professional Summary
    if (personalInfo.summary) {
      slide.addText('PROFESSIONAL SUMMARY', {
        x: 0.5, y: 1.8, w: 9, h: 0.4,
        fontSize: 14,
        bold: true,
        color: '2E4057'
      });
      
      slide.addText(personalInfo.summary, {
        x: 0.5, y: 2.2, w: 9, h: 1,
        fontSize: 11,
        color: '444444'
      });
    }
    
    // Experience
    if (experience && experience.length > 0) {
      slide.addText('EXPERIENCE', {
        x: 0.5, y: 3.4, w: 9, h: 0.4,
        fontSize: 14,
        bold: true,
        color: '2E4057'
      });
      
      let yPos = 3.8;
      experience.slice(0, 3).forEach(exp => {
        slide.addText(`${exp.position} - ${exp.company}`, {
          x: 0.5, y: yPos, w: 6, h: 0.3,
          fontSize: 12,
          bold: true,
          color: '444444'
        });
        
        slide.addText(exp.duration || '2020-2023', {
          x: 7, y: yPos, w: 2.5, h: 0.3,
          fontSize: 11,
          color: '666666',
          align: 'right'
        });
        
        if (exp.description) {
          slide.addText(exp.description, {
            x: 0.5, y: yPos + 0.3, w: 9, h: 0.4,
            fontSize: 10,
            color: '555555'
          });
        }
        
        yPos += 0.9;
      });
    }
    
    // Skills
    if (skills && skills.length > 0) {
      slide.addText('SKILLS', {
        x: 0.5, y: yPos + 0.2, w: 9, h: 0.4,
        fontSize: 14,
        bold: true,
        color: '2E4057'
      });
      
      slide.addText(skills.join(' • '), {
        x: 0.5, y: yPos + 0.6, w: 9, h: 0.6,
        fontSize: 11,
        color: '444444'
      });
    }
    
    // Save resume
    await pptx.writeFile({ fileName: filepath });
    
    const resumeUrl = `/uploads/${filename}`;
    
    // Save to database
    const mediaGen = new MediaGeneration({
      userId: req.userId,
      type: 'resume',
      prompt: `Resume: ${personalInfo.name || 'Professional Resume'}`,
      outputUrl: resumeUrl,
      metadata: { template, name: personalInfo.name }
    });
    
    await mediaGen.save();
    
    res.json({
      title: `Generated Resume: ${personalInfo.name || 'Professional Resume'}`,
      resumeUrl,
      filename,
      type: 'resume'
    });
  } catch (error) {
    res.status(500).json({ message: 'Resume generation failed', error: error.message });
  }
});

// Resume analysis using API
router.post('/resume-analyze', authenticateToken, async (req, res) => {
  try {
    const { resumeText, jobDescription } = req.body;
    
    if (!resumeText) {
      return res.status(400).json({ message: 'Resume text is required' });
    }
    
    // Analyze resume using the provided API
    const analysisResult = await analyzeResumeWithAPI(resumeText, jobDescription);
    
    res.json({
      title: 'Resume Analysis Complete',
      analysis: analysisResult,
      type: 'resume-analyze'
    });
  } catch (error) {
    res.status(500).json({ message: 'Resume analysis failed', error: error.message });
  }
});

// Get user's media generations
router.get('/history', authenticateToken, async (req, res) => {
  try {
    const generations = await MediaGeneration.find({ userId: req.userId })
      .sort({ createdAt: -1 })
      .limit(50);
    
    res.json(generations);
  } catch (error) {
    res.status(500).json({ message: 'Failed to fetch history', error: error.message });
  }
});

// Serve uploaded files
const uploadsPath = path.join(__dirname, '../uploads');
if (!fs.existsSync(uploadsPath)) {
  fs.mkdirSync(uploadsPath, { recursive: true });
}
router.use('/uploads', express.static(uploadsPath));

// Helper functions with AI API integration
async function generateTextResponse(prompt, context = []) {
  try {
    // Use the provided API key for ChatGPT-like responses
    const response = await getChatGPTResponse(prompt, context);
    return response;
  } catch (error) {
    console.error('AI API Error:', error.message);
    
    // Fallback to enhanced responses if API fails
    return getFallbackResponse(prompt);
  }
}

// ChatGPT-like AI response using the provided API key
async function getChatGPTResponse(prompt, context = []) {
  try {
    // Build conversation history for context
    const messages = [
      {
        role: "system",
        content: "You are Kris Bot, a professional multimodal AI assistant. You can help with conversations, generate images, create videos, build presentations, design resumes, and analyze existing resumes. Be helpful, concise, and professional in your responses."
      }
    ];

    // Add context from previous messages
    if (context && context.length > 0) {
      context.slice(-5).forEach(msg => {
        if (msg.role && msg.content) {
          messages.push({
            role: msg.role === 'assistant' ? 'assistant' : 'user',
            content: msg.content
          });
        }
      });
    }

    // Add current user message
    messages.push({
      role: "user",
      content: prompt
    });

    // Try multiple AI service endpoints with the provided API key
    const aiServices = [
      {
        url: 'https://api.apilayer.com/chat/completions',
        headers: {
          'apikey': process.env.RESUME_API_KEY || '8a7336db2c3d604e75d5f40543bde999',
          'Content-Type': 'application/json'
        }
      },
      {
        url: 'https://api.openai.com/v1/chat/completions',
        headers: {
          'Authorization': `Bearer ${process.env.RESUME_API_KEY || '8a7336db2c3d604e75d5f40543bde999'}`,
          'Content-Type': 'application/json'
        }
      }
    ];

    for (const service of aiServices) {
      try {
        const response = await axios.post(service.url, {
          model: "gpt-3.5-turbo",
          messages: messages,
          max_tokens: 1000,
          temperature: 0.7,
          top_p: 1,
          frequency_penalty: 0,
          presence_penalty: 0
        }, {
          headers: service.headers,
          timeout: 30000
        });

        if (response.data && response.data.choices && response.data.choices[0]) {
          return response.data.choices[0].message.content.trim();
        }
      } catch (serviceError) {
        console.log(`Service ${service.url} failed:`, serviceError.message);
        continue;
      }
    }

    // If all services fail, try a simpler approach
    const simpleResponse = await getSimpleAIResponse(prompt);
    return simpleResponse;

  } catch (error) {
    console.error('All AI services failed:', error.message);
    return getFallbackResponse(prompt);
  }
}

// Simple AI response using a different approach
async function getSimpleAIResponse(prompt) {
  try {
    // Try using the API key with a text completion endpoint
    const response = await axios.post('https://api.apilayer.com/text_completion', {
      prompt: `As Kris Bot, a professional AI assistant, respond to: "${prompt}"`,
      max_tokens: 500,
      temperature: 0.7
    }, {
      headers: {
        'apikey': '8a7336db2c3d604e75d5f40543bde999',
        'Content-Type': 'application/json'
      },
      timeout: 15000
    });

    if (response.data && response.data.text) {
      return response.data.text.trim();
    }

    return getFallbackResponse(prompt);
  } catch (error) {
    console.error('Simple AI response failed:', error.message);
    return getFallbackResponse(prompt);
  }
}

// Enhanced fallback responses
function getFallbackResponse(prompt) {
  const lowerPrompt = prompt.toLowerCase();
  
  // Greeting responses
  if (lowerPrompt.includes('hello') || lowerPrompt.includes('hi') || lowerPrompt.includes('hey') || lowerPrompt.includes('good morning') || lowerPrompt.includes('good afternoon')) {
    const greetings = [
      "Hello! I'm Kris Bot, your multimodal AI assistant. I can help you with conversations, generate images, create videos, build presentations, design resumes, and analyze existing resumes. How can I assist you today?",
      "Hi there! Welcome to Kris Bot. I'm here to help you with various tasks including text conversations, creative content generation, and professional document creation. What would you like to work on?",
      "Greetings! I'm Kris Bot, ready to assist you with AI-powered conversations, content creation, and professional services. Feel free to ask me anything or switch to other modes for specialized tasks."
    ];
    return greetings[Math.floor(Math.random() * greetings.length)];
  }

  // Help and capabilities
  if (lowerPrompt.includes('help') || lowerPrompt.includes('what can you do') || lowerPrompt.includes('capabilities') || lowerPrompt.includes('features')) {
    return "I can assist you in multiple ways:\n\n• **Text Conversations**: Engage in intelligent discussions and Q&A\n• **Image Generation**: Create stunning visuals from descriptions\n• **Video Creation**: Generate videos from prompts\n• **PowerPoint Presentations**: Build professional slide decks\n• **Resume Creation**: Design professional resumes\n• **Resume Analysis**: Analyze and provide feedback on existing resumes\n\nWhat specific task would you like help with?";
  }

  // Questions about AI/technology
  if (lowerPrompt.includes('ai') || lowerPrompt.includes('artificial intelligence') || lowerPrompt.includes('machine learning')) {
    return "I'm an AI assistant powered by advanced language models, designed to help you with various tasks. I can understand context, generate creative content, and provide professional assistance across multiple domains. Is there something specific about AI or technology you'd like to discuss?";
  }

  // Creative requests
  if (lowerPrompt.includes('create') || lowerPrompt.includes('generate') || lowerPrompt.includes('make') || lowerPrompt.includes('build')) {
    return "I'd be happy to help you create something! I can generate text content, help with presentations, create resumes, or assist with various creative projects. You can also switch to Image, Video, PPT, or Resume modes for specialized content creation. What would you like to create?";
  }

  // Questions
  if (lowerPrompt.includes('?') || lowerPrompt.includes('what') || lowerPrompt.includes('how') || lowerPrompt.includes('why') || lowerPrompt.includes('when') || lowerPrompt.includes('where')) {
    return `That's an interesting question about "${prompt}". While I'm currently operating with enhanced capabilities, I'm designed to provide thoughtful responses to a wide range of topics. I can help with explanations, analysis, creative tasks, and professional document creation. Could you provide more context about what specific information you're looking for?`;
  }

  // Default intelligent response
  const responses = [
    `I understand you're asking about "${prompt}". I'm here to help with that and much more! As Kris Bot, I can assist with conversations, content creation, and professional tasks. What specific aspect would you like to explore further?`,
    `Thanks for sharing "${prompt}" with me. I'm designed to provide helpful, intelligent responses across many topics. Whether you need assistance with analysis, creative projects, or professional documents, I'm here to help. How can I best assist you with this?`,
    `Regarding "${prompt}" - I'm processing this with my AI capabilities to provide you with the most helpful response possible. I can engage in detailed discussions, help with creative projects, or assist with professional tasks. What would be most useful for you right now?`
  ];

  return responses[Math.floor(Math.random() * responses.length)];
}

async function generateImage(prompt, style, size) {
  // Simulate image generation - replace with actual DALL-E/Midjourney API
  const [width, height] = size.split('x');
  const colors = ['4F46E5', '7C3AED', 'EC4899', '10B981', 'F59E0B', 'EF4444'];
  const bgColor = colors[Math.floor(Math.random() * colors.length)];
  const textColor = 'FFFFFF';
  const encodedPrompt = encodeURIComponent(prompt.substring(0, 25));
  
  return `https://via.placeholder.com/${width}x${height}/${bgColor}/${textColor}?text=AI+Generated:+${encodedPrompt}`;
}

async function generateVideo(prompt, style, duration, aspectRatio) {
  // Simulate video generation - replace with actual video AI API
  // In production, this would connect to services like Runway ML, Pika Labs, or Stable Video Diffusion
  const sampleVideos = [
    'https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'
  ];
  
  return sampleVideos[Math.floor(Math.random() * sampleVideos.length)];
}

// Resume analysis function using the provided API
async function analyzeResumeWithAPI(resumeText, jobDescription = '') {
  try {
    const formData = new FormData();
    formData.append('resume', resumeText);
    
    if (jobDescription) {
      formData.append('job_description', jobDescription);
    }
    
    const response = await axios.post(process.env.RESUME_API_URL, formData, {
      headers: {
        'apikey': process.env.RESUME_API_KEY,
        ...formData.getHeaders()
      }
    });
    
    const data = response.data;
    
    // Process and format the analysis
    return {
      personalInfo: {
        name: data.name || 'Not found',
        email: data.email || 'Not found',
        phone: data.phone || 'Not found',
        location: data.location || 'Not found'
      },
      experience: data.experience || [],
      education: data.education || [],
      skills: data.skills || [],
      summary: data.summary || 'No summary found',
      score: data.match_score || 0,
      recommendations: data.recommendations || [
        'Add more relevant keywords',
        'Include quantifiable achievements',
        'Improve formatting and structure',
        'Add missing contact information'
      ],
      strengths: data.strengths || [
        'Professional experience listed',
        'Educational background provided'
      ],
      improvements: data.improvements || [
        'Add more specific achievements',
        'Include relevant certifications',
        'Optimize for ATS systems'
      ]
    };
  } catch (error) {
    console.error('Resume API Error:', error.message);
    
    // Fallback analysis if API fails
    return {
      personalInfo: {
        name: 'Analysis in progress...',
        email: 'Please check resume format',
        phone: 'Not detected',
        location: 'Not specified'
      },
      experience: [],
      education: [],
      skills: extractSkillsFromText(resumeText),
      summary: 'Resume analysis completed with basic parsing',
      score: 75,
      recommendations: [
        'Ensure resume is in a supported format',
        'Include clear section headers',
        'Add quantifiable achievements',
        'Use standard resume formatting'
      ],
      strengths: [
        'Resume content provided',
        'Text is readable'
      ],
      improvements: [
        'Improve formatting for better parsing',
        'Add more structured information',
        'Include relevant keywords'
      ]
    };
  }
}

// Helper function to extract skills from text
function extractSkillsFromText(text) {
  const commonSkills = [
    'JavaScript', 'Python', 'Java', 'React', 'Node.js', 'HTML', 'CSS',
    'SQL', 'MongoDB', 'AWS', 'Docker', 'Git', 'Agile', 'Scrum',
    'Project Management', 'Leadership', 'Communication', 'Problem Solving'
  ];
  
  return commonSkills.filter(skill => 
    text.toLowerCase().includes(skill.toLowerCase())
  );
}

module.exports = router;